### ISSUE TITLE
Broken image links and missing images

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j-docs#129]
All of the images from the ND4J user guide are missing:
https://deeplearning4j.org/docs/latest/nd4j-overview
for example, c_vs_f_order.png semes to be gone entirely from the deeplearning4j-docs repo.

DL4J UI: https://deeplearning4j.org/docs/latest/deeplearning4j-nn-visualization

Also: https://deeplearning4j.org/docs/latest/deeplearning4j-nn-tsne-visualization

Not all pages are affected though: for example these seem fine:
https://deeplearning4j.org/docs/latest/deeplearning4j-spark-training
https://deeplearning4j.org/docs/latest/deeplearning4j-nn-early-stopping
https://deeplearning4j.org/docs/latest/deeplearning4j-nlp-word2vec
https://deeplearning4j.org/docs/latest/deeplearning4j-quickstart

## Due Date
*To be completed by:* YYYY-MM-DD

## Description
*Write a short description of what needs to be done.*

## Assignees
*Please ensure you have assigned at least one person to this issue. Include any authors and reviewers required.*

**Comment by crockpotveggies** [comment]
Hmm this is weird since I put in fixes for the images, and I just checked the source file and it shows that it's also fixed. I have a feeling someone generated some obsolete docs and dropped in an old version.

**Comment by crockpotveggies** [comment]
Looks like the live version is mistakenly using absolute links: https://raw.githubusercontent.com/deeplearning4j/deeplearning4j-docs/master/docs/_latest/deeplearning4j-nn-visualization.md

Checking master on our templates I can confirm it was fixed a while ago: https://github.com/deeplearning4j/deeplearning4j/commit/5e9b2a0c5d8d7f195d8ba5ac8c6dd31018adabce#diff-5b4bf74825b24fec818ef7e9cf9df6c6

I'll regenerate the docs and redeploy...

**Comment by crockpotveggies** [comment]
Should be fixed now. Please link and reopen if there's anything needing attention. https://deeplearning4j.org/docs/latest/deeplearning4j-nn-visualization

**Comment by treo** [comment]
Thery are still missing on https://deeplearning4j.org/docs/latest/nd4j-overview

**Comment by crockpotveggies** [comment]
Migrated images from the ND4J gh-pages branch. Fixed those now.
